/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as PlayRouteImport } from './routes/play'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as BetRouteImport } from './routes/bet'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PvpIdRouteImport } from './routes/pvp.$id'
import { Route as ApiPublicV1SettleRouteImport } from './routes/api/public/v1/settle'
import { Route as ApiPublicV1RollbackRouteImport } from './routes/api/public/v1/rollback'
import { Route as ApiPublicV1PingRouteImport } from './routes/api/public/v1/ping'
import { Route as ApiPublicV1BetRouteImport } from './routes/api/public/v1/bet'
import { Route as ApiPublicV1BalanceRouteImport } from './routes/api/public/v1/balance'
import { Route as ApiPublicPixCallbackRouteImport } from './routes/api/public/pix.callback'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const BetRoute = BetRouteImport.update({
  id: '/bet',
  path: '/bet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PvpIdRoute = PvpIdRouteImport.update({
  id: '/pvp/$id',
  path: '/pvp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SettleRoute = ApiPublicV1SettleRouteImport.update({
  id: '/api/public/v1/settle',
  path: '/api/public/v1/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RollbackRoute = ApiPublicV1RollbackRouteImport.update({
  id: '/api/public/v1/rollback',
  path: '/api/public/v1/rollback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PingRoute = ApiPublicV1PingRouteImport.update({
  id: '/api/public/v1/ping',
  path: '/api/public/v1/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BetRoute = ApiPublicV1BetRouteImport.update({
  id: '/api/public/v1/bet',
  path: '/api/public/v1/bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BalanceRoute = ApiPublicV1BalanceRouteImport.update({
  id: '/api/public/v1/balance',
  path: '/api/public/v1/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixCallbackRoute = ApiPublicPixCallbackRouteImport.update({
  id: '/api/public/pix/callback',
  path: '/api/public/pix/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auth': typeof AuthRoute
  '/bet': typeof BetRoute
  '/desafios': typeof DesafiosRoute
  '/historico': typeof HistoricoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/play': typeof PlayRoute
  '/recompensas': typeof RecompensasRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/pvp/$id': typeof PvpIdRoute
  '/api/public/pix/callback': typeof ApiPublicPixCallbackRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/bet': typeof ApiPublicV1BetRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/rollback': typeof ApiPublicV1RollbackRoute
  '/api/public/v1/settle': typeof ApiPublicV1SettleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auth': typeof AuthRoute
  '/bet': typeof BetRoute
  '/desafios': typeof DesafiosRoute
  '/historico': typeof HistoricoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/play': typeof PlayRoute
  '/recompensas': typeof RecompensasRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/pvp/$id': typeof PvpIdRoute
  '/api/public/pix/callback': typeof ApiPublicPixCallbackRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/bet': typeof ApiPublicV1BetRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/rollback': typeof ApiPublicV1RollbackRoute
  '/api/public/v1/settle': typeof ApiPublicV1SettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auth': typeof AuthRoute
  '/bet': typeof BetRoute
  '/desafios': typeof DesafiosRoute
  '/historico': typeof HistoricoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/play': typeof PlayRoute
  '/recompensas': typeof RecompensasRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/pvp/$id': typeof PvpIdRoute
  '/api/public/pix/callback': typeof ApiPublicPixCallbackRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/bet': typeof ApiPublicV1BetRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/rollback': typeof ApiPublicV1RollbackRoute
  '/api/public/v1/settle': typeof ApiPublicV1SettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ao-vivo'
    | '/auth'
    | '/bet'
    | '/desafios'
    | '/historico'
    | '/notificacoes'
    | '/play'
    | '/recompensas'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/pvp/$id'
    | '/api/public/pix/callback'
    | '/api/public/v1/balance'
    | '/api/public/v1/bet'
    | '/api/public/v1/ping'
    | '/api/public/v1/rollback'
    | '/api/public/v1/settle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ao-vivo'
    | '/auth'
    | '/bet'
    | '/desafios'
    | '/historico'
    | '/notificacoes'
    | '/play'
    | '/recompensas'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/pvp/$id'
    | '/api/public/pix/callback'
    | '/api/public/v1/balance'
    | '/api/public/v1/bet'
    | '/api/public/v1/ping'
    | '/api/public/v1/rollback'
    | '/api/public/v1/settle'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ao-vivo'
    | '/auth'
    | '/bet'
    | '/desafios'
    | '/historico'
    | '/notificacoes'
    | '/play'
    | '/recompensas'
    | '/shop'
    | '/sitemap.xml'
    | '/social'
    | '/pvp/$id'
    | '/api/public/pix/callback'
    | '/api/public/v1/balance'
    | '/api/public/v1/bet'
    | '/api/public/v1/ping'
    | '/api/public/v1/rollback'
    | '/api/public/v1/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AoVivoRoute: typeof AoVivoRoute
  AuthRoute: typeof AuthRoute
  BetRoute: typeof BetRoute
  DesafiosRoute: typeof DesafiosRoute
  HistoricoRoute: typeof HistoricoRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PlayRoute: typeof PlayRoute
  RecompensasRoute: typeof RecompensasRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  PvpIdRoute: typeof PvpIdRoute
  ApiPublicPixCallbackRoute: typeof ApiPublicPixCallbackRoute
  ApiPublicV1BalanceRoute: typeof ApiPublicV1BalanceRoute
  ApiPublicV1BetRoute: typeof ApiPublicV1BetRoute
  ApiPublicV1PingRoute: typeof ApiPublicV1PingRoute
  ApiPublicV1RollbackRoute: typeof ApiPublicV1RollbackRoute
  ApiPublicV1SettleRoute: typeof ApiPublicV1SettleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet': {
      id: '/bet'
      path: '/bet'
      fullPath: '/bet'
      preLoaderRoute: typeof BetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pvp/$id': {
      id: '/pvp/$id'
      path: '/pvp/$id'
      fullPath: '/pvp/$id'
      preLoaderRoute: typeof PvpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/settle': {
      id: '/api/public/v1/settle'
      path: '/api/public/v1/settle'
      fullPath: '/api/public/v1/settle'
      preLoaderRoute: typeof ApiPublicV1SettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/rollback': {
      id: '/api/public/v1/rollback'
      path: '/api/public/v1/rollback'
      fullPath: '/api/public/v1/rollback'
      preLoaderRoute: typeof ApiPublicV1RollbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ping': {
      id: '/api/public/v1/ping'
      path: '/api/public/v1/ping'
      fullPath: '/api/public/v1/ping'
      preLoaderRoute: typeof ApiPublicV1PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/bet': {
      id: '/api/public/v1/bet'
      path: '/api/public/v1/bet'
      fullPath: '/api/public/v1/bet'
      preLoaderRoute: typeof ApiPublicV1BetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/balance': {
      id: '/api/public/v1/balance'
      path: '/api/public/v1/balance'
      fullPath: '/api/public/v1/balance'
      preLoaderRoute: typeof ApiPublicV1BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/callback': {
      id: '/api/public/pix/callback'
      path: '/api/public/pix/callback'
      fullPath: '/api/public/pix/callback'
      preLoaderRoute: typeof ApiPublicPixCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AoVivoRoute: AoVivoRoute,
  AuthRoute: AuthRoute,
  BetRoute: BetRoute,
  DesafiosRoute: DesafiosRoute,
  HistoricoRoute: HistoricoRoute,
  NotificacoesRoute: NotificacoesRoute,
  PlayRoute: PlayRoute,
  RecompensasRoute: RecompensasRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  PvpIdRoute: PvpIdRoute,
  ApiPublicPixCallbackRoute: ApiPublicPixCallbackRoute,
  ApiPublicV1BalanceRoute: ApiPublicV1BalanceRoute,
  ApiPublicV1BetRoute: ApiPublicV1BetRoute,
  ApiPublicV1PingRoute: ApiPublicV1PingRoute,
  ApiPublicV1RollbackRoute: ApiPublicV1RollbackRoute,
  ApiPublicV1SettleRoute: ApiPublicV1SettleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
